### ISSUE TITLE
Questions about privacy budget

### ISSUE THREAD

**Issue by simra** [GODqinbin/DPBoost#6]
Hi, I'm working on a binary classification task and trying to understand the privacy accounting.  It looks like the accounting approach uses simple sequential composition here: https://github.com/QinbinLi/DPBoost/blob/683938e5cad756e09b29fd4805a9833d54ca790b/src/boosting/gbdt.cpp#L634 

Initially I expected that after `num_iterations` the `global_total_budget` would sum to the `total_budget` defined in the configuration.  However, at each round of DPBoost_2Level, the current budget is calculated as `total_budget * inner_boost_round /(2* num_iterations)`  (a combination of lines 572 and 624, assuming `num_iterations` is evenly divided by `inner_boost_round`. So the final privacy budget spent will differ from total_budget by a factor of `inner_boost_round/2`.  Is this expected?

Here are the lines that compute `current_budget`:
https://github.com/QinbinLi/DPBoost/blob/683938e5cad756e09b29fd4805a9833d54ca790b/src/boosting/gbdt.cpp#L571-L572
https://github.com/QinbinLi/DPBoost/blob/683938e5cad756e09b29fd4805a9833d54ca790b/src/boosting/gbdt.cpp#L624

**Comment by QinbinLi** [comment]
Hi @simra ,

Sorry for the confusion. The variable `global_total_budget` is an out-of-date variable and is not used in the code. I have removed it in the latest version. The `total_budget` is the total privacy budget given to DPBoost and the current budget is the budget given for the current `inner_boost_round` (since parallel composition is applied inside a `inner_boost_round`).
